force-app/main/default/objects/Post__c.object
<CustomObject>
    <fields>
        <fullName>Author_Writer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Author/Writer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Posts</relationshipLabel>
        <relationshipName>Posts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Approved__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Post</label>
    <nameField>
        <label>Post Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SendPostForReviewEmailsBatch.cls
global class SendPostForReviewEmailsBatch implements Database.Batchable<sObject>, Database.Stateful {
    
    @TestVisible
    global Integer emailsSent = 0;
    
    global List<Id> managers = new List<Id>();
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        system.debug('reached batch');
        return Database.getQueryLocator('SELECT Id, Author_Writer__c, Author_Writer__r.OwnerId FROM Post__c WHERE Status__c = \'Under Review\'');
    }
                                        
    global void execute(Database.BatchableContext bc, List<Post__c> scope) {
        system.debug('reached execute with: ' + scope.size());
        for(Post__c pendingPost : scope) {
            if(!managers.contains(pendingPost.Author_Writer__r.OwnerId)) {
                managers.add(pendingPost.Author_Writer__r.OwnerId);
            }
        }
        system.debug('authors with owner: ' + managers.size());
        List<Messaging.Email> emailMessages = new List<Messaging.Email>();
        
        For(Id manager : managers) {
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTargetObjectId(manager);
            mail.setTemplateId('00X3i000000h0b9EAA');
            mail.setTreatTargetObjectAsRecipient(true);
            mail.setSaveAsActivity(false);
            
            emailMessages.add(mail);
        }
        system.debug('emails sent: ' + emailMessages.size());
        emailsSent = emailMessages.size();
        Messaging.sendEmail(emailMessages);
        
    }
    
    global void finish(Database.BatchableContext bc) {
        
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
        
        System.debug('Emails sent: ' + emailsSent + ' Job: ' + job);
        
    }

}