force-app/main/default/objects/Post__c.object
<CustomObject>
    <fields>
        <fullName>Author_Writer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Author/Writer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Posts</relationshipLabel>
        <relationshipName>Posts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <label>Published Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Approved__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tags__c</fullName>
        <label>Tags</label>
        <type>TextArea</type>
    </fields>
    <label>Post</label>
    <nameField>
        <label>Post Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MarkdownContentController.cls
public class MarkdownContentController {
    
    @AuraEnabled
    public static Boolean updatePost(Id postId, String newContent) {
        if(newContent != null && newContent != '') {
            Post__c currentPost = new Post__c();
            
            try {
                currentPost = [SELECT Id, Name, Content__c, Status__c, Published_Date__c, Tags__c, Author_Writer__c FROM Post__c WHERE Id = : postId];
                currentPost.Content__c = newContent;
                update currentPost;
                
            } catch(DmlException e) {
                System.debug('An unexpected error has occurred: ' + e.getMessage());
                return false;
            }
            
            return true;
        }
        
        return false;
    }
    
    @AuraEnabled
    public static String submitForReview(Id postId) {
        Post__c currentPost = new Post__c();
        String result = 'Now your post is under review';
        
        try {
            currentPost = [SELECT Id, Name, Status__c, Published_Date__c, Tags__c, Author_Writer__c FROM Post__c WHERE Id = : postId];
            if(currentPost.Status__c == 'Draft') {
                currentPost.Status__c = 'Under Review';
                update currentPost;
                return result;
            }
            else {
                System.debug('Only post with status "Draft" can be set under review.');
                result = 'Only post with status "Draft" can be set under review.';
                return result;
            }
            
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
            result = 'Error when trying to update post status.';
            return result;
        }
    }

}