force-app/main/default/objects/Work_Item__c.object
<CustomObject>
    <fields>
        <fullName>Difficulty_Level__c</fullName>
        <label>Difficulty Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work Item</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/WorkItemBoardController.cls
public class WorkItemBoardController {
    
    @AuraEnabled
    public static dataResult retrieveWIData() {
        dataResult result = new dataResult();
        result.statusColumns = loadWIStatusColumns();
        result.wItems = getWorkItems();
        return result;
    }
    
    public class dataResult {
        
        @AuraEnabled
        public List<String> statusColumns {get; set;}
        
        @AuraEnabled
        public List<Work_Item__c> wItems {get; set;}
         
    }
    
    @AuraEnabled
    public static List<String> loadWIStatusColumns() {
        
        List<String> statusPicklistValues = new List<String>();
        
        Schema.DescribeFieldResult field = Work_Item__c.Status__c.getDescribe();
        List<Schema.PicklistEntry> entries = field.getPicklistValues();
        for(Schema.PicklistEntry entry : entries) {
            statusPicklistValues.add(entry.getLabel());
        }
        return statusPicklistValues;
    }
    
    @AuraEnabled
    public static List<Work_Item__c> getWorkItems() {
        Date beginDate = Date.today().addDays(-30);
        List<Work_Item__c> wItems = [SELECT Id, Name, Difficulty_Level__c, RecordType.Name, Status__c From Work_Item__c where Start_Date__c >= :beginDate];
        return wItems;
    }

}